export const FETCH_PRODUCT="FETCH_PRODUCT";
export const ADD_PRODUCT="ADD_PRODUCT";
export const EDIT_PRODUCT="EDIT_PRODUCT";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const CHANGE_INPUT="CHANGE_INPUT";
export const SUBMIT_FORM_ADD="SUBMIT_FORM_ADD";

export const SUBMIT_FORM_EDIT="SUBMIT_FORM_EDIT";
